if(NOT DEFINED INPUT_DIR)
    message(FATAL_ERROR "INPUT_DIR is required")
endif()

if(NOT DEFINED OUTPUT_CPP)
    message(FATAL_ERROR "OUTPUT_CPP is required")
endif()

if(NOT DEFINED OUTPUT_H)
    message(FATAL_ERROR "OUTPUT_H is required")
endif()

file(TO_CMAKE_PATH "${INPUT_DIR}" NORMALIZED_INPUT_DIR)
file(GLOB_RECURSE RESOURCE_FILES LIST_DIRECTORIES false "${NORMALIZED_INPUT_DIR}/*")
list(SORT RESOURCE_FILES)

function(to_cpp_bytes input_hex output_var)
    string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1, " cpp_bytes "${input_hex}")
    set(${output_var} "${cpp_bytes}" PARENT_SCOPE)
endfunction()

file(WRITE "${OUTPUT_H}" "#pragma once\n\n")
file(APPEND "${OUTPUT_H}" "#include <cstddef>\n")
file(APPEND "${OUTPUT_H}" "#include <span>\n")
file(APPEND "${OUTPUT_H}" "#include <string_view>\n\n")
file(APPEND "${OUTPUT_H}" "namespace keyrecord {\n\n")
file(APPEND "${OUTPUT_H}" "struct EmbeddedResourceEntry {\n")
file(APPEND "${OUTPUT_H}" "    std::string_view path;\n")
file(APPEND "${OUTPUT_H}" "    const unsigned char* data;\n")
file(APPEND "${OUTPUT_H}" "    std::size_t size;\n")
file(APPEND "${OUTPUT_H}" "};\n\n")
file(APPEND "${OUTPUT_H}" "std::span<const EmbeddedResourceEntry> generatedEmbeddedResources();\n\n")
file(APPEND "${OUTPUT_H}" "} // namespace keyrecord\n")

get_filename_component(OUTPUT_H_NAME "${OUTPUT_H}" NAME)
file(WRITE "${OUTPUT_CPP}" "#include \"${OUTPUT_H_NAME}\"\n\n")
file(APPEND "${OUTPUT_CPP}" "namespace keyrecord {\nnamespace {\n\n")

set(RESOURCE_ENTRIES "")
foreach(RESOURCE_FILE IN LISTS RESOURCE_FILES)
    file(RELATIVE_PATH RELATIVE_RESOURCE_PATH "${NORMALIZED_INPUT_DIR}" "${RESOURCE_FILE}")
    string(REPLACE "\\" "/" RELATIVE_RESOURCE_PATH "${RELATIVE_RESOURCE_PATH}")
    set(RESOURCE_PATH "/${RELATIVE_RESOURCE_PATH}")
    string(MAKE_C_IDENTIFIER "${RELATIVE_RESOURCE_PATH}" RESOURCE_IDENTIFIER)
    set(ARRAY_NAME "resource_${RESOURCE_IDENTIFIER}")

    file(READ "${RESOURCE_FILE}" RESOURCE_HEX HEX)
    to_cpp_bytes("${RESOURCE_HEX}" RESOURCE_BYTES)

    file(APPEND "${OUTPUT_CPP}" "constexpr unsigned char ${ARRAY_NAME}[] = { ${RESOURCE_BYTES} };\n\n")
    string(APPEND RESOURCE_ENTRIES "    { \"${RESOURCE_PATH}\", ${ARRAY_NAME}, sizeof(${ARRAY_NAME}) },\n")
endforeach()

file(APPEND "${OUTPUT_CPP}" "constexpr EmbeddedResourceEntry kResources[] = {\n")
file(APPEND "${OUTPUT_CPP}" "${RESOURCE_ENTRIES}")
file(APPEND "${OUTPUT_CPP}" "};\n\n")
file(APPEND "${OUTPUT_CPP}" "} // namespace\n\n")
file(APPEND "${OUTPUT_CPP}" "std::span<const EmbeddedResourceEntry> generatedEmbeddedResources() {\n")
file(APPEND "${OUTPUT_CPP}" "    return std::span<const EmbeddedResourceEntry>(kResources, sizeof(kResources) / sizeof(kResources[0]));\n")
file(APPEND "${OUTPUT_CPP}" "}\n\n")
file(APPEND "${OUTPUT_CPP}" "} // namespace keyrecord\n")
